///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TeamMembersModelPlayer {
/*
{
  "idPlayer": "34219745",
  "strNationality": "United States",
  "strPlayer": "AJ Griffin",
  "dateBorn": "2003-08-25",
  "strNumber": "14",
  "strBirthLocation": "Dallas, Texas, U.S.",
  "strDescriptionEN": "Adrian Darnell \"AJ\" Griffin Jr. (born August 25, 2003) is an American professional basketball player for the Atlanta Hawks of the National Basketball Association (NBA). He played college basketball for the Duke Blue Devils.",
  "strGender": "Male",
  "strPosition": "Shooting Guard",
  "strHeight": "6 ft 6 in (1.98 m)",
  "strWeight": "220 lb (100 kg)",
  "strThumb": "https://www.thesportsdb.com/images/media/player/thumb/tcyrsc1688751406.jpg",
  "strCutout": "https://www.thesportsdb.com/images/media/player/cutout/r6ny101688751496.png",
  "strRender": "https://www.thesportsdb.com/images/media/player/render/9pd7ml1688751448.png"
}
*/

  String? idPlayer;
  String? strNationality;
  String? strPlayer;
  String? dateBorn;
  String? strNumber;
  String? strBirthLocation;
  String? strDescriptionEN;
  String? strGender;
  String? strPosition;
  String? strHeight;
  String? strWeight;
  String? strThumb;
  String? strCutout;
  String? strRender;

  TeamMembersModelPlayer({
    this.idPlayer,
    this.strNationality,
    this.strPlayer,
    this.dateBorn,
    this.strNumber,
    this.strBirthLocation,
    this.strDescriptionEN,
    this.strGender,
    this.strPosition,
    this.strHeight,
    this.strWeight,
    this.strThumb,
    this.strCutout,
    this.strRender,
  });
  TeamMembersModelPlayer.fromJson(Map<String, dynamic> json) {
    idPlayer = json['idPlayer']?.toString();
    strNationality = json['strNationality']?.toString();
    strPlayer = json['strPlayer']?.toString();
    dateBorn = json['dateBorn']?.toString();
    strNumber = json['strNumber']?.toString();
    strBirthLocation = json['strBirthLocation']?.toString();
    strDescriptionEN = json['strDescriptionEN']?.toString();
    strGender = json['strGender']?.toString();
    strPosition = json['strPosition']?.toString();
    strHeight = json['strHeight']?.toString();
    strWeight = json['strWeight']?.toString();
    strThumb = json['strThumb']?.toString();
    strCutout = json['strCutout']?.toString();
    strRender = json['strRender']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['idPlayer'] = idPlayer;
    data['strNationality'] = strNationality;
    data['strPlayer'] = strPlayer;
    data['dateBorn'] = dateBorn;
    data['strNumber'] = strNumber;
    data['strBirthLocation'] = strBirthLocation;
    data['strDescriptionEN'] = strDescriptionEN;
    data['strGender'] = strGender;
    data['strPosition'] = strPosition;
    data['strHeight'] = strHeight;
    data['strWeight'] = strWeight;
    data['strThumb'] = strThumb;
    data['strCutout'] = strCutout;
    data['strRender'] = strRender;
    return data;
  }
}

class TeamMembersModel {
/*
{
  "player": [
    {
      "idPlayer": "34219745",
      "strNationality": "United States",
      "strPlayer": "AJ Griffin",
      "dateBorn": "2003-08-25",
      "strNumber": "14",
      "strBirthLocation": "Dallas, Texas, U.S.",
      "strDescriptionEN": "Adrian Darnell \"AJ\" Griffin Jr. (born August 25, 2003) is an American professional basketball player for the Atlanta Hawks of the National Basketball Association (NBA). He played college basketball for the Duke Blue Devils.",
      "strGender": "Male",
      "strPosition": "Shooting Guard",
      "strHeight": "6 ft 6 in (1.98 m)",
      "strWeight": "220 lb (100 kg)",
      "strThumb": "https://www.thesportsdb.com/images/media/player/thumb/tcyrsc1688751406.jpg",
      "strCutout": "https://www.thesportsdb.com/images/media/player/cutout/r6ny101688751496.png",
      "strRender": "https://www.thesportsdb.com/images/media/player/render/9pd7ml1688751448.png"
    }
  ]
}
*/

  List<TeamMembersModelPlayer?>? player;

  TeamMembersModel({
    this.player,
  });
  TeamMembersModel.fromJson(Map<String, dynamic> json) {
    if (json['player'] != null) {
      final v = json['player'];
      final arr0 = <TeamMembersModelPlayer>[];
      v.forEach((v) {
        arr0.add(TeamMembersModelPlayer.fromJson(v));
      });
      player = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (player != null) {
      final v = player;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['player'] = arr0;
    }
    return data;
  }
}
