///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FormerTeamModelFormerteams {
/*
{
  "id": "8154",
  "idPlayer": "34162046",
  "idFormerTeam": "136102",
  "strSport": "Basketball",
  "strPlayer": "Bogdan Bogdanović",
  "strFormerTeam": "KK Partizan",
  "strMoveType": "Permanent",
  "strTeamBadge": "https://www.thesportsdb.com/images/media/team/badge/j3fpvj1521150793.png",
  "strJoined": "2010",
  "strDeparted": "2014"
}
*/

  String? id;
  String? idPlayer;
  String? idFormerTeam;
  String? strSport;
  String? strPlayer;
  String? strFormerTeam;
  String? strMoveType;
  String? strTeamBadge;
  String? strJoined;
  String? strDeparted;

  FormerTeamModelFormerteams({
    this.id,
    this.idPlayer,
    this.idFormerTeam,
    this.strSport,
    this.strPlayer,
    this.strFormerTeam,
    this.strMoveType,
    this.strTeamBadge,
    this.strJoined,
    this.strDeparted,
  });
  FormerTeamModelFormerteams.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    idPlayer = json['idPlayer']?.toString();
    idFormerTeam = json['idFormerTeam']?.toString();
    strSport = json['strSport']?.toString();
    strPlayer = json['strPlayer']?.toString();
    strFormerTeam = json['strFormerTeam']?.toString();
    strMoveType = json['strMoveType']?.toString();
    strTeamBadge = json['strTeamBadge']?.toString();
    strJoined = json['strJoined']?.toString();
    strDeparted = json['strDeparted']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['idPlayer'] = idPlayer;
    data['idFormerTeam'] = idFormerTeam;
    data['strSport'] = strSport;
    data['strPlayer'] = strPlayer;
    data['strFormerTeam'] = strFormerTeam;
    data['strMoveType'] = strMoveType;
    data['strTeamBadge'] = strTeamBadge;
    data['strJoined'] = strJoined;
    data['strDeparted'] = strDeparted;
    return data;
  }
}

class FormerTeamModel {
/*
{
  "formerteams": [
    {
      "id": "8154",
      "idPlayer": "34162046",
      "idFormerTeam": "136102",
      "strSport": "Basketball",
      "strPlayer": "Bogdan Bogdanović",
      "strFormerTeam": "KK Partizan",
      "strMoveType": "Permanent",
      "strTeamBadge": "https://www.thesportsdb.com/images/media/team/badge/j3fpvj1521150793.png",
      "strJoined": "2010",
      "strDeparted": "2014"
    }
  ]
}
*/

  List<FormerTeamModelFormerteams?>? formerteams;

  FormerTeamModel({
    this.formerteams,
  });
  FormerTeamModel.fromJson(Map<String, dynamic> json) {
    if (json['formerteams'] != null) {
      final v = json['formerteams'];
      final arr0 = <FormerTeamModelFormerteams>[];
      v.forEach((v) {
        arr0.add(FormerTeamModelFormerteams.fromJson(v));
      });
      formerteams = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (formerteams != null) {
      final v = formerteams;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['formerteams'] = arr0;
    }
    return data;
  }
}
