///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HonoursModelHonours {
/*
{
  "id": "38640",
  "idPlayer": "34162046",
  "idTeam": "136071",
  "strSport": "Basketball",
  "strPlayer": "Bogdan Bogdanović",
  "strTeam": "Fenerbahçe Basketbol",
  "strHonour": "FIBA EuroLeague",
  "strSeason": "2016-2017",
  "intChecked": "1"
}
*/

  String? id;
  String? idPlayer;
  String? idTeam;
  String? strSport;
  String? strPlayer;
  String? strTeam;
  String? strHonour;
  String? strSeason;
  String? intChecked;

  HonoursModelHonours({
    this.id,
    this.idPlayer,
    this.idTeam,
    this.strSport,
    this.strPlayer,
    this.strTeam,
    this.strHonour,
    this.strSeason,
    this.intChecked,
  });
  HonoursModelHonours.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    idPlayer = json['idPlayer']?.toString();
    idTeam = json['idTeam']?.toString();
    strSport = json['strSport']?.toString();
    strPlayer = json['strPlayer']?.toString();
    strTeam = json['strTeam']?.toString();
    strHonour = json['strHonour']?.toString();
    strSeason = json['strSeason']?.toString();
    intChecked = json['intChecked']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['idPlayer'] = idPlayer;
    data['idTeam'] = idTeam;
    data['strSport'] = strSport;
    data['strPlayer'] = strPlayer;
    data['strTeam'] = strTeam;
    data['strHonour'] = strHonour;
    data['strSeason'] = strSeason;
    data['intChecked'] = intChecked;
    return data;
  }
}

class HonoursModel {
/*
{
  "honours": [
    {
      "id": "38640",
      "idPlayer": "34162046",
      "idTeam": "136071",
      "strSport": "Basketball",
      "strPlayer": "Bogdan Bogdanović",
      "strTeam": "Fenerbahçe Basketbol",
      "strHonour": "FIBA EuroLeague",
      "strSeason": "2016-2017",
      "intChecked": "1"
    }
  ]
}
*/

  List<HonoursModelHonours?>? honours;

  HonoursModel({
    this.honours,
  });
  HonoursModel.fromJson(Map<String, dynamic> json) {
    if (json['honours'] != null) {
      final v = json['honours'];
      final arr0 = <HonoursModelHonours>[];
      v.forEach((v) {
        arr0.add(HonoursModelHonours.fromJson(v));
      });
      honours = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (honours != null) {
      final v = honours;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['honours'] = arr0;
    }
    return data;
  }
}
