///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MilestonesModelMilestones {
/*
{
  "idMilestone": "2120",
  "idPlayer": "34162046",
  "strPlayer": "Bogdan Bogdanović",
  "idTeam": "136733",
  "strTeam": "Serbia Basketball",
  "strSport": "Basketball",
  "strMilestone": "EuroBasket All-Tournament Team",
  "strMilestoneLogo": "https://www.thesportsdb.com/images/media/milestone/logo/1rnzoa1663700026.png",
  "dateMilestone": "2017-09-17"
}
*/

  String? idMilestone;
  String? idPlayer;
  String? strPlayer;
  String? idTeam;
  String? strTeam;
  String? strSport;
  String? strMilestone;
  String? strMilestoneLogo;
  String? dateMilestone;

  MilestonesModelMilestones({
    this.idMilestone,
    this.idPlayer,
    this.strPlayer,
    this.idTeam,
    this.strTeam,
    this.strSport,
    this.strMilestone,
    this.strMilestoneLogo,
    this.dateMilestone,
  });
  MilestonesModelMilestones.fromJson(Map<String, dynamic> json) {
    idMilestone = json['idMilestone']?.toString();
    idPlayer = json['idPlayer']?.toString();
    strPlayer = json['strPlayer']?.toString();
    idTeam = json['idTeam']?.toString();
    strTeam = json['strTeam']?.toString();
    strSport = json['strSport']?.toString();
    strMilestone = json['strMilestone']?.toString();
    strMilestoneLogo = json['strMilestoneLogo']?.toString();
    dateMilestone = json['dateMilestone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['idMilestone'] = idMilestone;
    data['idPlayer'] = idPlayer;
    data['strPlayer'] = strPlayer;
    data['idTeam'] = idTeam;
    data['strTeam'] = strTeam;
    data['strSport'] = strSport;
    data['strMilestone'] = strMilestone;
    data['strMilestoneLogo'] = strMilestoneLogo;
    data['dateMilestone'] = dateMilestone;
    return data;
  }
}

class MilestonesModel {
/*
{
  "milestones": [
    {
      "idMilestone": "2120",
      "idPlayer": "34162046",
      "strPlayer": "Bogdan Bogdanović",
      "idTeam": "136733",
      "strTeam": "Serbia Basketball",
      "strSport": "Basketball",
      "strMilestone": "EuroBasket All-Tournament Team",
      "strMilestoneLogo": "https://www.thesportsdb.com/images/media/milestone/logo/1rnzoa1663700026.png",
      "dateMilestone": "2017-09-17"
    }
  ]
}
*/

  List<MilestonesModelMilestones?>? milestones;

  MilestonesModel({
    this.milestones,
  });
  MilestonesModel.fromJson(Map<String, dynamic> json) {
    if (json['milestones'] != null) {
      final v = json['milestones'];
      final arr0 = <MilestonesModelMilestones>[];
      v.forEach((v) {
        arr0.add(MilestonesModelMilestones.fromJson(v));
      });
      milestones = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (milestones != null) {
      final v = milestones;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['milestones'] = arr0;
    }
    return data;
  }
}
