///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MLSStandingsModelData {
/*
{
  "StandingId": 15967,
  "RoundId": 1057,
  "TeamId": 1539,
  "Name": "FC Cincinnati",
  "ShortName": "Cincinnati",
  "Scope": "Total",
  "Order": 1,
  "Games": 33,
  "Wins": 20,
  "Losses": 5,
  "Draws": 8,
  "GoalsScored": 55,
  "GoalsAgainst": 37,
  "GoalsDifferential": 18,
  "Points": 68,
  "Group": "Eastern Conference",
  "GlobalTeamID": 90001539
}
*/

  int? StandingId;
  int? RoundId;
  int? TeamId;
  String? Name;
  String? ShortName;
  String? Scope;
  int? ConferenceRank;
  num? Games;
  num? Wins;
  num? Losses;
  num? Draws;
  int? GoalsScored;
  int? GoalsAgainst;
  num? GoalsDifferential;
  num? Points;
  String? Conference;
  int? GlobalTeamID;

  MLSStandingsModelData({
    this.StandingId,
    this.RoundId,
    this.TeamId,
    this.Name,
    this.ShortName,
    this.Scope,
    this.ConferenceRank,
    this.Games,
    this.Wins,
    this.Losses,
    this.Draws,
    this.GoalsScored,
    this.GoalsAgainst,
    this.GoalsDifferential,
    this.Points,
    this.Conference,
    this.GlobalTeamID,
  });

  MLSStandingsModelData.fromJson(Map<String, dynamic> json) {
    StandingId = json['StandingId']?.toInt();
    RoundId = json['RoundId']?.toInt();
    TeamId = json['TeamId']?.toInt();
    Name = json['Name']?.toString();
    ShortName = json['ShortName']?.toString();
    Scope = json['Scope']?.toString();
    ConferenceRank = json['Order']?.toInt();
    Games = json['Games']?.toInt();
    Wins = json['Wins']?.toInt();
    Losses = json['Losses']?.toInt();
    Draws = json['Draws']?.toInt();
    GoalsScored = json['GoalsScored']?.toInt();
    GoalsAgainst = json['GoalsAgainst']?.toInt();
    GoalsDifferential = json['GoalsDifferential']?.toInt();
    Points = json['Points']?.toInt();
    Conference = json['Group']?.toString();
    GlobalTeamID = json['GlobalTeamID']?.toInt();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['StandingId'] = StandingId;
    data['RoundId'] = RoundId;
    data['TeamId'] = TeamId;
    data['Name'] = Name;
    data['ShortName'] = ShortName;
    data['Scope'] = Scope;
    data['Order'] = ConferenceRank;
    data['Games'] = Games;
    data['Wins'] = Wins;
    data['Losses'] = Losses;
    data['Draws'] = Draws;
    data['GoalsScored'] = GoalsScored;
    data['GoalsAgainst'] = GoalsAgainst;
    data['GoalsDifferential'] = GoalsDifferential;
    data['Points'] = Points;
    data['Group'] = Conference;
    data['GlobalTeamID'] = GlobalTeamID;
    return data;
  }
}

class MLSStandingsModel {
/*
{
  "data": [
    {
      "StandingId": 15967,
      "RoundId": 1057,
      "TeamId": 1539,
      "Name": "FC Cincinnati",
      "ShortName": "Cincinnati",
      "Scope": "Total",
      "Order": 1,
      "Games": 33,
      "Wins": 20,
      "Losses": 5,
      "Draws": 8,
      "GoalsScored": 55,
      "GoalsAgainst": 37,
      "GoalsDifferential": 18,
      "Points": 68,
      "Group": "Eastern Conference",
      "GlobalTeamID": 90001539
    }
  ]
}
*/

  List<MLSStandingsModelData?>? data;

  MLSStandingsModel({
    this.data,
  });

  MLSStandingsModel.fromJson(Map<String, dynamic> json) {
    //MLSStandingsModelData _mlsStandingModelData;
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <MLSStandingsModelData>[];
      v.forEach((v) {
        //arr0.add(MLSStandingsModelData.fromJson(v));
       // print("Scope:${v["Scope"]}");
        if (v["Scope"] == "Total") {
          print("True");
          arr0.add(MLSStandingsModelData.fromJson(v));
        }
      });
      this.data = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
