///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NFLStandingsModelData {
/*
{
  "SeasonType": 1,
  "Season": 2023,
  "Conference": "AFC",
  "Division": "East",
  "Team": "MIA",
  "Name": "Miami Dolphins",
  "Wins": 5,
  "Losses": 1,
  "Ties": 0,
  "Percentage": 0.833,
  "PointsFor": 223,
  "PointsAgainst": 156,
  "NetPoints": 67,
  "Touchdowns": 30,
  "DivisionWins": 1,
  "DivisionLosses": 1,
  "ConferenceWins": 3,
  "ConferenceLosses": 1,
  "TeamID": 19,
  "DivisionTies": 0,
  "ConferenceTies": 0,
  "GlobalTeamID": 19,
  "DivisionRank": 1,
  "ConferenceRank": 2
}
*/

  int? SeasonType;
  int? Season;
  String? Conference;
  String? Division;
  String? Team;
  String? Name;
  num? Wins;
  num? Losses;
  num? Ties;
  String? Percentage;
  num? PointsFor;
  num? PointsAgainst;
  num? NetPoints;
  num? Touchdowns;
  int? DivisionWins;
  int? DivisionLosses;
  int? ConferenceWins;
  int? ConferenceLosses;
  int? TeamID;
  int? DivisionTies;
  int? ConferenceTies;
  int? GlobalTeamID;
  int? DivisionRank;
  int? ConferenceRank;

  NFLStandingsModelData({
    this.SeasonType,
    this.Season,
    this.Conference,
    this.Division,
    this.Team,
    this.Name,
    this.Wins,
    this.Losses,
    this.Ties,
    this.Percentage,
    this.PointsFor,
    this.PointsAgainst,
    this.NetPoints,
    this.Touchdowns,
    this.DivisionWins,
    this.DivisionLosses,
    this.ConferenceWins,
    this.ConferenceLosses,
    this.TeamID,
    this.DivisionTies,
    this.ConferenceTies,
    this.GlobalTeamID,
    this.DivisionRank,
    this.ConferenceRank,
  });
  NFLStandingsModelData.fromJson(Map<String, dynamic> json) {
    SeasonType = json['SeasonType']?.toInt();
    Season = json['Season']?.toInt();
    Conference = json['Conference']?.toString();
    Division = json['Division']?.toString();
    Team = json['Team']?.toString();
    Name = json['Name']?.toString();
    Wins = json['Wins']?.toInt();
    Losses = json['Losses']?.toInt();
    Ties = json['Ties']?.toInt();
    Percentage = json['Percentage']?.toStringAsFixed(2);
    PointsFor = json['PointsFor']?.toInt();
    PointsAgainst = json['PointsAgainst']?.toInt();
    NetPoints = json['NetPoints']?.toInt();
    Touchdowns = json['Touchdowns']?.toInt();
    DivisionWins = json['DivisionWins']?.toInt();
    DivisionLosses = json['DivisionLosses']?.toInt();
    ConferenceWins = json['ConferenceWins']?.toInt();
    ConferenceLosses = json['ConferenceLosses']?.toInt();
    TeamID = json['TeamID']?.toInt();
    DivisionTies = json['DivisionTies']?.toInt();
    ConferenceTies = json['ConferenceTies']?.toInt();
    GlobalTeamID = json['GlobalTeamID']?.toInt();
    DivisionRank = json['DivisionRank']?.toInt();
    ConferenceRank = json['ConferenceRank']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['SeasonType'] = SeasonType;
    data['Season'] = Season;
    data['Conference'] = Conference;
    data['Division'] = Division;
    data['Team'] = Team;
    data['Name'] = Name;
    data['Wins'] = Wins;
    data['Losses'] = Losses;
    data['Ties'] = Ties;
    data['Percentage'] = Percentage;
    data['PointsFor'] = PointsFor;
    data['PointsAgainst'] = PointsAgainst;
    data['NetPoints'] = NetPoints;
    data['Touchdowns'] = Touchdowns;
    data['DivisionWins'] = DivisionWins;
    data['DivisionLosses'] = DivisionLosses;
    data['ConferenceWins'] = ConferenceWins;
    data['ConferenceLosses'] = ConferenceLosses;
    data['TeamID'] = TeamID;
    data['DivisionTies'] = DivisionTies;
    data['ConferenceTies'] = ConferenceTies;
    data['GlobalTeamID'] = GlobalTeamID;
    data['DivisionRank'] = DivisionRank;
    data['ConferenceRank'] = ConferenceRank;
    return data;
  }
}

class NFLStandingsModel {
/*
{
  "data": [
    {
      "SeasonType": 1,
      "Season": 2023,
      "Conference": "AFC",
      "Division": "East",
      "Team": "MIA",
      "Name": "Miami Dolphins",
      "Wins": 5,
      "Losses": 1,
      "Ties": 0,
      "Percentage": 0.833,
      "PointsFor": 223,
      "PointsAgainst": 156,
      "NetPoints": 67,
      "Touchdowns": 30,
      "DivisionWins": 1,
      "DivisionLosses": 1,
      "ConferenceWins": 3,
      "ConferenceLosses": 1,
      "TeamID": 19,
      "DivisionTies": 0,
      "ConferenceTies": 0,
      "GlobalTeamID": 19,
      "DivisionRank": 1,
      "ConferenceRank": 2
    }
  ]
}
*/

  List<NFLStandingsModelData?>? data;

  NFLStandingsModel({
    this.data,
  });
  NFLStandingsModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <NFLStandingsModelData>[];
      v.forEach((v) {
        arr0.add(NFLStandingsModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
