///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TeamStandingsModelDataConferenceData {
/*
{
  "team_rank": "Rank",
  "team_name": "Teams",
  "division_name": "Division Name",
  "field_one": "GP",
  "field_two": "W",
  "field_three": "L",
  "field_four": "OT",
  "field_five": "PTS"
}
*/

  String? teamRank;
  String? teamName;
  String? divisionName;
  String? fieldOne;
  String? fieldTwo;
  String? fieldThree;
  String? fieldFour;
  String? fieldFive;

  TeamStandingsModelDataConferenceData({
    this.teamRank,
    this.teamName,
    this.divisionName,
    this.fieldOne,
    this.fieldTwo,
    this.fieldThree,
    this.fieldFour,
    this.fieldFive,
  });
  TeamStandingsModelDataConferenceData.fromJson(Map<String, dynamic> json) {
    teamRank = json['team_rank']?.toString();
    teamName = json['team_name']?.toString();
    divisionName = json['division_name']?.toString();
    fieldOne = json['field_one']?.toString();
    fieldTwo = json['field_two']?.toString();
    fieldThree = json['field_three']?.toString();
    fieldFour = json['field_four']?.toString();
    fieldFive = json['field_five']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['team_rank'] = teamRank;
    data['team_name'] = teamName;
    data['division_name'] = divisionName;
    data['field_one'] = fieldOne;
    data['field_two'] = fieldTwo;
    data['field_three'] = fieldThree;
    data['field_four'] = fieldFour;
    data['field_five'] = fieldFive;
    return data;
  }
}

class TeamStandingsModelData {
/*
{
  "conference_name": "Eastern",
  "conference_id": 1,
  "conference_data": [
    {
      "team_rank": "Rank",
      "team_name": "Teams",
      "division_name": "Division Name",
      "field_one": "GP",
      "field_two": "W",
      "field_three": "L",
      "field_four": "OT",
      "field_five": "PTS"
    }
  ]
}
*/

  String? conferenceName;
  int? conferenceId;
  List<TeamStandingsModelDataConferenceData?>? conferenceData;

  TeamStandingsModelData({
    this.conferenceName,
    this.conferenceId,
    this.conferenceData,
  });
  TeamStandingsModelData.fromJson(Map<String, dynamic> json) {
    conferenceName = json['conference_name']?.toString();
    conferenceId = json['conference_id']?.toInt();
    if (json['conference_data'] != null) {
      final v = json['conference_data'];
      final arr0 = <TeamStandingsModelDataConferenceData>[];
      v.forEach((v) {
        arr0.add(TeamStandingsModelDataConferenceData.fromJson(v));
      });
      conferenceData = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['conference_name'] = conferenceName;
    data['conference_id'] = conferenceId;
    if (conferenceData != null) {
      final v = conferenceData;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['conference_data'] = arr0;
    }
    return data;
  }
}

class TeamStandingsModel {
/*
{
  "data": [
    {
      "conference_name": "Eastern",
      "conference_id": 1,
      "conference_data": [
        {
          "team_rank": "Rank",
          "team_name": "Teams",
          "division_name": "Division Name",
          "field_one": "GP",
          "field_two": "W",
          "field_three": "L",
          "field_four": "OT",
          "field_five": "PTS"
        }
      ]
    }
  ]
}
*/

  List<TeamStandingsModelData?>? data;

  TeamStandingsModel({
    this.data,
  });
  TeamStandingsModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <TeamStandingsModelData>[];
      v.forEach((v) {
        arr0.add(TeamStandingsModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
