///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LeaguesModelData {
/*
{
  "idLeague": 4387,
  "strLeague": "NBA",
  "strSport": "Basketball",
  "strLeagueAlternate": "National Basketball Association",
  "strLeagueName": "National Basketball Association",
  "strLeagueSport": "Basketball",
  "strLeagueAbbreviation": "NBA",
  "strLeagueImage": "league_images/NBA.jpeg"
}
*/

  int? idLeague;
  String? strLeague;
  String? strSport;
  String? strLeagueAlternate;
  String? strLeagueName;
  String? strLeagueSport;
  String? strLeagueAbbreviation;
  String? strLeagueImage;

  LeaguesModelData({
    this.idLeague,
    this.strLeague,
    this.strSport,
    this.strLeagueAlternate,
    this.strLeagueName,
    this.strLeagueSport,
    this.strLeagueAbbreviation,
    this.strLeagueImage,
  });
  LeaguesModelData.fromJson(Map<String, dynamic> json) {
    idLeague = json['idLeague']?.toInt();
    strLeague = json['strLeague']?.toString();
    strSport = json['strSport']?.toString();
    strLeagueAlternate = json['strLeagueAlternate']?.toString();
    strLeagueName = json['strLeagueName']?.toString();
    strLeagueSport = json['strLeagueSport']?.toString();
    strLeagueAbbreviation = json['strLeagueAbbreviation']?.toString();
    strLeagueImage = json['strLeagueImage']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['idLeague'] = idLeague;
    data['strLeague'] = strLeague;
    data['strSport'] = strSport;
    data['strLeagueAlternate'] = strLeagueAlternate;
    data['strLeagueName'] = strLeagueName;
    data['strLeagueSport'] = strLeagueSport;
    data['strLeagueAbbreviation'] = strLeagueAbbreviation;
    data['strLeagueImage'] = strLeagueImage;
    return data;
  }
}

class LeaguesModel {
/*
{
  "status": 1,
  "message": "leagues",
  "data": [
    {
      "idLeague": 4387,
      "strLeague": "NBA",
      "strSport": "Basketball",
      "strLeagueAlternate": "National Basketball Association",
      "strLeagueName": "National Basketball Association",
      "strLeagueSport": "Basketball",
      "strLeagueAbbreviation": "NBA",
      "strLeagueImage": "league_images/NBA.jpeg"
    }
  ]
}
*/

  int? status;
  String? message;
  List<LeaguesModelData?>? data;

  LeaguesModel({
    this.status,
    this.message,
    this.data,
  });
  LeaguesModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <LeaguesModelData>[];
      v.forEach((v) {
        arr0.add(LeaguesModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
