///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SeasonsModelSeasons {
/*
{
  "strSeason": "1966-1967"
}
*/

  String? strSeason;

  SeasonsModelSeasons({
    this.strSeason,
  });
  SeasonsModelSeasons.fromJson(Map<String, dynamic> json) {
    strSeason = json['strSeason']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['strSeason'] = strSeason;
    return data;
  }
}

class SeasonsModel {
/*
{
  "seasons": [
    {
      "strSeason": "1966-1967"
    }
  ]
}
*/

  List<SeasonsModelSeasons?>? seasons;

  SeasonsModel({
    this.seasons,
  });
  SeasonsModel.fromJson(Map<String, dynamic> json) {
    if (json['seasons'] != null) {
      final v = json['seasons'];
      final arr0 = <SeasonsModelSeasons>[];
      v.forEach((v) {
        arr0.add(SeasonsModelSeasons.fromJson(v));
      });
      seasons = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (seasons != null) {
      final v = seasons;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['seasons'] = arr0;
    }
    return data;
  }
}
