///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TeamsModelTeams {
/*
{
  "idTeam": "134880",
  "strTeam": "Atlanta Hawks",
  "strTeamShort": "ATL",
  "strAlternate": "",
  "strSport": "Basketball",
  "strDescriptionEN": "dfdf",
  "strCountry": "United States",
  "strTeamBadge": "https://www.thesportsdb.com/images/media/team/badge/xqtvvp1422380623.png",
  "strTeamJersey": "https://www.thesportsdb.com/images/media/team/jersey/2oyak71508680738.png",
  "strTeamLogo": "https://www.thesportsdb.com/images/media/team/logo/95xe4a1571252558.png",
  "strTeamFanart1": "https://www.thesportsdb.com/images/media/team/fanart/rptxyq1420549311.jpg",
  "strTeamBanner": "https://www.thesportsdb.com/images/media/team/banner/xuxtyv1420740260.jpg"
}
*/

  String? idTeam;
  String? strTeam;
  String? strTeamShort;
  String? strAlternate;
  String? strSport;
  String? strDescriptionEN;
  String? strCountry;
  String? strTeamBadge;
  String? strTeamJersey;
  String? strTeamLogo;
  String? strTeamFanart1;
  String? strTeamBanner;

  TeamsModelTeams({
    this.idTeam,
    this.strTeam,
    this.strTeamShort,
    this.strAlternate,
    this.strSport,
    this.strDescriptionEN,
    this.strCountry,
    this.strTeamBadge,
    this.strTeamJersey,
    this.strTeamLogo,
    this.strTeamFanart1,
    this.strTeamBanner,
  });
  TeamsModelTeams.fromJson(Map<String, dynamic> json) {
    idTeam = json['idTeam']?.toString();
    strTeam = json['strTeam']?.toString();
    strTeamShort = json['strTeamShort']?.toString();
    strAlternate = json['strAlternate']?.toString();
    strSport = json['strSport']?.toString();
    strDescriptionEN = json['strDescriptionEN']?.toString();
    strCountry = json['strCountry']?.toString();
    strTeamBadge = json['strTeamBadge']?.toString();
    strTeamJersey = json['strTeamJersey']?.toString();
    strTeamLogo = json['strTeamLogo']?.toString();
    strTeamFanart1 = json['strTeamFanart1']?.toString();
    strTeamBanner = json['strTeamBanner']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['idTeam'] = idTeam;
    data['strTeam'] = strTeam;
    data['strTeamShort'] = strTeamShort;
    data['strAlternate'] = strAlternate;
    data['strSport'] = strSport;
    data['strDescriptionEN'] = strDescriptionEN;
    data['strCountry'] = strCountry;
    data['strTeamBadge'] = strTeamBadge;
    data['strTeamJersey'] = strTeamJersey;
    data['strTeamLogo'] = strTeamLogo;
    data['strTeamFanart1'] = strTeamFanart1;
    data['strTeamBanner'] = strTeamBanner;
    return data;
  }
}

class TeamsModel {
/*
{
  "teams": [
    {
      "idTeam": "134880",
      "strTeam": "Atlanta Hawks",
      "strTeamShort": "ATL",
      "strAlternate": "",
      "strSport": "Basketball",
      "strDescriptionEN": "dfdf",
      "strCountry": "United States",
      "strTeamBadge": "https://www.thesportsdb.com/images/media/team/badge/xqtvvp1422380623.png",
      "strTeamJersey": "https://www.thesportsdb.com/images/media/team/jersey/2oyak71508680738.png",
      "strTeamLogo": "https://www.thesportsdb.com/images/media/team/logo/95xe4a1571252558.png",
      "strTeamFanart1": "https://www.thesportsdb.com/images/media/team/fanart/rptxyq1420549311.jpg",
      "strTeamBanner": "https://www.thesportsdb.com/images/media/team/banner/xuxtyv1420740260.jpg"
    }
  ]
}
*/

  List<TeamsModelTeams?>? teams;

  TeamsModel({
    this.teams,
  });
  TeamsModel.fromJson(Map<String, dynamic> json) {
    if (json['teams'] != null) {
      final v = json['teams'];
      final arr0 = <TeamsModelTeams>[];
      v.forEach((v) {
        arr0.add(TeamsModelTeams.fromJson(v));
      });
      teams = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (teams != null) {
      final v = teams;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['teams'] = arr0;
    }
    return data;
  }
}
