///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserModelData {
/*
{
  "id": 2,
  "otp": null,
  "first_name": "Demo",
  "last_name": "User1",
  "email": "demouser@getnada.com",
  "email_verified_at": "2023-10-10T11:07:49.000000Z",
  "phone_number": "1234567899",
  "phone_code": "+1",
  "country_code": "US",
  "profile_image": "profile_image/WpbmgtxIwNVr6g9cc1SHr9lVoYsllLlUe7i1voBz.jpg",
  "account_verified": 1,
  "device_type": "android",
  "device_token": null,
  "is_social": 0,
  "user_social_token": null,
  "user_social_type": null,
  "is_profile_complete": 1,
  "is_blocked": 0,
  "notifications": 1,
  "deleted_at": null,
  "created_at": "2023-10-10T11:06:01.000000Z",
  "updated_at": "2023-10-10T11:08:12.000000Z"
}
*/

  int? id;
  String? otp;
  String? firstName;
  String? lastName;
  String? email;
  String? emailVerifiedAt;
  String? phoneNumber;
  String? phoneCode;
  String? countryCode;
  String? profileImage;
  int? accountVerified;
  String? deviceType;
  String? deviceToken;
  int? isSocial;
  String? userSocialToken;
  String? userSocialType;
  int? isProfileComplete;
  int? isBlocked;
  int? notifications;
  String? deletedAt;
  String? createdAt;
  String? updatedAt;

  UserModelData({
    this.id,
    this.otp,
    this.firstName,
    this.lastName,
    this.email,
    this.emailVerifiedAt,
    this.phoneNumber,
    this.phoneCode,
    this.countryCode,
    this.profileImage,
    this.accountVerified,
    this.deviceType,
    this.deviceToken,
    this.isSocial,
    this.userSocialToken,
    this.userSocialType,
    this.isProfileComplete,
    this.isBlocked,
    this.notifications,
    this.deletedAt,
    this.createdAt,
    this.updatedAt,
  });
  UserModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    otp = json['otp']?.toString();
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    email = json['email']?.toString();
    emailVerifiedAt = json['email_verified_at']?.toString();
    phoneNumber = json['phone_number']?.toString();
    phoneCode = json['phone_code']?.toString();
    countryCode = json['country_code']?.toString();
    profileImage = json['profile_image']?.toString();
    accountVerified = json['account_verified']?.toInt();
    deviceType = json['device_type']?.toString();
    deviceToken = json['device_token']?.toString();
    isSocial = json['is_social']?.toInt();
    userSocialToken = json['user_social_token']?.toString();
    userSocialType = json['user_social_type']?.toString();
    isProfileComplete = json['is_profile_complete']?.toInt();
    isBlocked = json['is_blocked']?.toInt();
    notifications = json['notifications']?.toInt();
    deletedAt = json['deleted_at']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['otp'] = otp;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['email'] = email;
    data['email_verified_at'] = emailVerifiedAt;
    data['phone_number'] = phoneNumber;
    data['phone_code'] = phoneCode;
    data['country_code'] = countryCode;
    data['profile_image'] = profileImage;
    data['account_verified'] = accountVerified;
    data['device_type'] = deviceType;
    data['device_token'] = deviceToken;
    data['is_social'] = isSocial;
    data['user_social_token'] = userSocialToken;
    data['user_social_type'] = userSocialType;
    data['is_profile_complete'] = isProfileComplete;
    data['is_blocked'] = isBlocked;
    data['notifications'] = notifications;
    data['deleted_at'] = deletedAt;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class UserModel {
/*
{
  "status": 1,
  "message": "Profile completed successfully.",
  "data": {
    "id": 2,
    "otp": null,
    "first_name": "Demo",
    "last_name": "User1",
    "email": "demouser@getnada.com",
    "email_verified_at": "2023-10-10T11:07:49.000000Z",
    "phone_number": "1234567899",
    "phone_code": "+1",
    "country_code": "US",
    "profile_image": "profile_image/WpbmgtxIwNVr6g9cc1SHr9lVoYsllLlUe7i1voBz.jpg",
    "account_verified": 1,
    "device_type": "android",
    "device_token": null,
    "is_social": 0,
    "user_social_token": null,
    "user_social_type": null,
    "is_profile_complete": 1,
    "is_blocked": 0,
    "notifications": 1,
    "deleted_at": null,
    "created_at": "2023-10-10T11:06:01.000000Z",
    "updated_at": "2023-10-10T11:08:12.000000Z"
  }
} 
*/

  int? status;
  String? message;
  UserModelData? data;

  UserModel({
    this.status,
    this.message,
    this.data,
  });
  UserModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null) ? UserModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
