///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NewsModelArticlesImages {
/*
{
  "name": "Roger Goodell [1296x729]",
  "width": 1296,
  "caption": "NFL Commissioner Roger Goodell said Europe would better suit an entire division, rather than a single franchise.",
  "id": 34890260,
  "credit": "Wesley Hitt/Getty Images",
  "type": "header",
  "url": "https://a.espncdn.com/photo/2022/1027/r1082091_1296x729_16-9.jpg",
  "height": 729
}
*/

  String? name;
  int? width;
  String? caption;
  int? id;
  String? credit;
  String? type;
  String? url;
  int? height;

  NewsModelArticlesImages({
    this.name,
    this.width,
    this.caption,
    this.id,
    this.credit,
    this.type,
    this.url,
    this.height,
  });
  NewsModelArticlesImages.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    width = json['width']?.toInt();
    caption = json['caption']?.toString();
    id = json['id']?.toInt();
    credit = json['credit']?.toString();
    type = json['type']?.toString();
    url = json['url']?.toString();
    height = json['height']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['width'] = width;
    data['caption'] = caption;
    data['id'] = id;
    data['credit'] = credit;
    data['type'] = type;
    data['url'] = url;
    data['height'] = height;
    return data;
  }
}

class NewsModelArticles {
/*
{
  "description": "NFL commissioner Roger Goodell has had his contract extended through March 2027. It is the third extension for Goodell since he took on the job in 2006.",
  "headline": "NFL commissioner Roger Goodell receives 3-year extension",
  "images": [
    {
      "name": "Roger Goodell [1296x729]",
      "width": 1296,
      "caption": "NFL Commissioner Roger Goodell said Europe would better suit an entire division, rather than a single franchise.",
      "id": 34890260,
      "credit": "Wesley Hitt/Getty Images",
      "type": "header",
      "url": "https://a.espncdn.com/photo/2022/1027/r1082091_1296x729_16-9.jpg",
      "height": 729
    }
  ],
  "published": "2023-10-18T15:19:16Z",
  "lastModified": "2023-10-18T15:19:15Z"
}
*/

  String? description;
  String? headline;
  List<NewsModelArticlesImages?>? images;
  String? published;
  String? lastModified;

  NewsModelArticles({
    this.description,
    this.headline,
    this.images,
    this.published,
    this.lastModified,
  });
  NewsModelArticles.fromJson(Map<String, dynamic> json) {
    description = json['description']?.toString();
    headline = json['headline']?.toString();
    if (json['images'] != null) {
      final v = json['images'];
      final arr0 = <NewsModelArticlesImages>[];
      v.forEach((v) {
        arr0.add(NewsModelArticlesImages.fromJson(v));
      });
      images = arr0;
    }
    published = json['published']?.toString();
    lastModified = json['lastModified']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['description'] = description;
    data['headline'] = headline;
    if (images != null) {
      final v = images;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['images'] = arr0;
    }
    data['published'] = published;
    data['lastModified'] = lastModified;
    return data;
  }
}

class NewsModel {
/*
{
  "articles": [
    {
      "description": "NFL commissioner Roger Goodell has had his contract extended through March 2027. It is the third extension for Goodell since he took on the job in 2006.",
      "headline": "NFL commissioner Roger Goodell receives 3-year extension",
      "images": [
        {
          "name": "Roger Goodell [1296x729]",
          "width": 1296,
          "caption": "NFL Commissioner Roger Goodell said Europe would better suit an entire division, rather than a single franchise.",
          "id": 34890260,
          "credit": "Wesley Hitt/Getty Images",
          "type": "header",
          "url": "https://a.espncdn.com/photo/2022/1027/r1082091_1296x729_16-9.jpg",
          "height": 729
        }
      ],
      "published": "2023-10-18T15:19:16Z",
      "lastModified": "2023-10-18T15:19:15Z"
    }
  ]
}
*/

  List<NewsModelArticles?>? articles;

  NewsModel({
    this.articles,
  });
  NewsModel.fromJson(Map<String, dynamic> json) {
    if (json['articles'] != null) {
      final v = json['articles'];
      final arr0 = <NewsModelArticles>[];
      v.forEach((v) {
        arr0.add(NewsModelArticles.fromJson(v));
      });
      articles = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (articles != null) {
      final v = articles;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['articles'] = arr0;
    }
    return data;
  }
}
